title: jimmydong / 老董
description: 工作不闲聊
social:
  - title: GitHub
    img: /assets/images/github.ico
    url: https://github.com/jimmydong
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:jimmydong@gmail.com

avatar: /assets/images/avatar.jpg
introduction: >
  Hi! I am jimmydong.<br/>
  Welcome to my site!

projects:
  title: Open Source Projects
  github:
    - jimmydong/YEPF3
    - jimmydong/jd-init
    - jimmydong/DBM
    - jimmydong/YEPY
    - jimmydong/Yaf
  content: >
    <p>Other projects that I have contributed can be found in <a href="https://github.com/jimmydong">github.com/jimmydong</a>.</p>

working:
  title: Working Experience
  timeline:
    - date: Now
    - "Yishengdaojia.com: CTO"
    - date: 2015-02
    - "Yoka.com: Director"
    - date: 2008-12
    - "SOHU.com: Tech Manager"
    - date: 2005-08
    - "Other: Senior Engineer"
    - date: 1999-08

education:
  title: Education Background
  timeline:
    - date: 2008-07
    - "Master of Peking University: Computer Networking"
    - date: 1999-07
    - "Bachelor of University of Science and Technology of China: Computer Science and Technology"
    - date: 1994-09

google_analytics: justwait
